{% set name = "pychooch" %}
{% set version = "5.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mxcube/pychooch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3dfb79095f44d7215427df5fc084551e6cf8928d8e844fc2accbd255b8b3c735

build:
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - python
    - pip
    - setuptools
    - gsl
    - libblas
    - plplot
  run:
    - python

test:
  imports:
    - PyChooch
  source_files:
    - test_pychooch.py
    - CHOOCH_TEST.raw
  commands:
    - python test_pychooch.py CHOOCH_TEST.raw

about:
  home: https://github.com/mxcube/pychooch
  summary: 'Python binding to chooch, a program for calculating anomalous scattering factors from X-ray fluorescence spectra'
  license: GPL-2.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/mxcube/pychooch

extra:
  recipe-maintainers:
    - beenje
